import Foundation

/// Manages the creation of the generation piplines
final class GenerationPipelineManager {
    static let global: GenerationPipelineManager = .init()

    /// Creates one or more pipelines if a model should be generated by a template file
    ///
    /// - Parameter generateFromTemplateArgument: The object containing neccessary information about the tempaltes
    func queue(generateFromTemplateArgument: GenerateFromTemplateArgument) {
        let templateURLs: [URL] = InputFileExtractor.extractInputFiles(from: generateFromTemplateArgument)

        for templateURL in templateURLs {
            GenerationPipeline().run(with: templateURL, output: generateFromTemplateArgument.modelPath.url)
        }
    }

    /// Creates one pipeline for a provided inline model
    ///
    /// - Parameter generateModelArgument: The object containing the inline model template
    func queue(generateModelArgument: GenerateModelArgument) {

    }
}
